### ISSUE TITLE
CSS way to find out where the window controls are

### ISSUE THREAD

**Issue by tomayac** [WICG/window-controls-overlay#14]
Currently there is no CSS way to find out if the window controls are on the left (e.g., macOS) or on the right (e.g., Windows). It would be great if this were somehow exposed. The use case is the following:

Assume we have a PWA whose theme color is red:

```html
<meta name="theme-color" content="red">
```

We have a window controls overlay that gets styled with CSS:

```html
<div class="window-controls-overlay">
  <!-- Some content -->
</div>
```

```css
.window-controls-overlay {
  background-image: linear-gradient(90deg, blue, red);
  /* Actual styling */
}
```

This background image will blend in with the red theme color nicely on Windows, but the linear gradient needs to be flipped on macOS. This can be realized _programmatically_ by checking `const {x} = navigator.windowControlsOverlay.getBoundingClientRect()` and applying classes with the linear gradient running in the right direction dynamically, but it were nicer to be able to do this _declaratively_.

Ideally there were a way to do this in CSS, for example, via a pair of pseudo-classes `::window-controls-left` and `::window-controls-right`:

```css
.window-controls-overlay::window-controls-right {
  background-image: linear-gradient(90deg, blue, red);
  /* Actual styling */
}

.window-controls-overlay::window-controls-left {
  background-image: linear-gradient(90deg, red, blue);
  /* Actual styling */
}
```

Alternatively with current window managers who either have the window controls on the left or the right, having just one pseudo-class would suffice to determine the other, but a more future-proof design may be to make it explicit in case at some point in the future `::window-controls-middle` (or whatever else) is needed…
