### ISSUE TITLE
How to disable rubber-band scrolling in MacOS

### ISSUE THREAD

**Issue by mantou132** [WICG/window-controls-overlay#21]
<img width="1159" alt="Screen Shot 2021-08-28 at 1 13 35 PM" src="https://user-images.githubusercontent.com/3841872/131207119-a72a6b3c-83fd-49d5-8889-3203ca71cc70.png">

**Comment by tomayac** [comment]
You can do this in CSS:

```css

html {
  height: 100%;
  width: 100%;
  overflow: hidden;
}

body {
  height: 100%;
  padding: 0;
  overflow: auto;
  margin: 0;
  -webkit-overflow-scrolling: touch;
}
```
